export PATH=$PWD/bin:$PATH
export LD_LIBRARY_PATH=$PWD/CI/lib:$PWD/CI/src:$LD_LIBRARY_PATH
export PYTHONPATH=$HOME/CMSCI/python:$PYTHONPATH
export LHAPDF_DATA_PATH=$HOME/external/share/LHAPDF/PDFsets

